(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a}; 
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this),ea="function"===typeof Symbol&&"symbol"===typeof Symbol("x"),q={},fa={};function r(a,b){var c=fa[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]} 
function u(a,b,c){if(b)a:{var d=a.split(".");a=1===d.length;var e=d[0],f;!a&&e in q?f=q:f=da;for(e=0;e<d.length-1;e++){var g=d[e];if(!(g in f))break a;f=f[g]}d=d[d.length-1];c=ea&&"es6"===c?f[d]:null;b=b(c);null!=b&&(a?ba(q,d,{configurable:!0,writable:!0,value:b}):b!==c&&(fa[d]=ea?da.Symbol(d):"$jscp$"+d,d=fa[d],ba(f,d,{configurable:!0,writable:!0,value:b})))}} 
u("Symbol",function(a){function b(e){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(e||"")+"_"+d++,e)}function c(e,f){this.a=e;ba(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.a};var d=0;return b},"es6"); 
u("Symbol.iterator",function(a){if(a)return a;a=(0,q.Symbol)("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ha(aa(this))}})}return a},"es6"); 
function ha(a){a={next:a};a[r(q.Symbol,"iterator")]=function(){return this};return a}function ia(a){return a.raw=a}function y(a){var b="undefined"!=typeof q.Symbol&&r(q.Symbol,"iterator")&&a[r(q.Symbol,"iterator")];return b?b.call(a):{next:aa(a)}}function ja(a){if(!(a instanceof Array)){a=y(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ka="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},la; 
if(ea&&"function"==typeof Object.setPrototypeOf)la=Object.setPrototypeOf;else{var ma;a:{var na={La:!0},oa={};try{oa.__proto__=na;ma=oa.La;break a}catch(a){}ma=!1}la=ma?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var pa=la; 
function z(a,b){a.prototype=ka(b.prototype);a.prototype.constructor=a;if(pa)pa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.cb=b.prototype} 
function qa(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}u("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=qa(this,b,"endsWith");void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}},"es6"); 
function ra(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{wa:e,Ka:f}}return{wa:-1,Ka:void 0}}u("Array.prototype.find",function(a){return a?a:function(b,c){return ra(this,b,c).Ka}},"es6");u("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=qa(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var g=0;g<f&&c<e;)if(d[c++]!=b[g++])return!1;return g>=f}},"es6"); 
function sa(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var ta=ea&&"function"==typeof r(Object,"assign")?r(Object,"assign"):function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)sa(d,e)&&(a[e]=d[e])}return a};u("Object.assign",function(a){return a||ta},"es6"); 
u("Promise",function(a){function b(g){this.a=0;this.f=void 0;this.c=[];this.v=!1;var h=this.g();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.a=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.c=function(g){if(null==this.a){this.a=[];var h=this;this.f(function(){h.h()})}this.a.push(g)};var e=da.setTimeout;c.prototype.f=function(g){e(g,0)};c.prototype.h=function(){for(;this.a&&this.a.length;){var g=this.a;this.a=[];for(var h=0;h<g.length;++h){var k= 
g[h];g[h]=null;try{k()}catch(l){this.g(l)}}}this.a=null};c.prototype.g=function(g){this.f(function(){throw g;})};b.prototype.g=function(){function g(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:g(this.K),reject:g(this.h)}};b.prototype.K=function(g){if(g===this)this.h(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.M(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=!1}h?this.I(g):this.j(g)}}; 
b.prototype.I=function(g){var h=void 0;try{h=g.then}catch(k){this.h(k);return}"function"==typeof h?this.N(h,g):this.j(g)};b.prototype.h=function(g){this.m(2,g)};b.prototype.j=function(g){this.m(1,g)};b.prototype.m=function(g,h){if(0!=this.a)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.a);this.a=g;this.f=h;2===this.a&&this.L();this.C()};b.prototype.L=function(){var g=this;e(function(){if(g.H()){var h=da.console;"undefined"!==typeof h&&h.error(g.f)}},1)};b.prototype.H= 
function(){if(this.v)return!1;var g=da.CustomEvent,h=da.Event,k=da.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof g?g=new g("unhandledrejection",{cancelable:!0}):"function"===typeof h?g=new h("unhandledrejection",{cancelable:!0}):(g=da.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.f;return k(g)};b.prototype.C=function(){if(null!=this.c){for(var g=0;g<this.c.length;++g)f.c(this.c[g]);this.c=null}};var f=new c; 
b.prototype.M=function(g){var h=this.g();g.ca(h.resolve,h.reject)};b.prototype.N=function(g,h){var k=this.g();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(g,h){function k(t,v){return"function"==typeof t?function(x){try{l(t(x))}catch(w){m(w)}}:v}var l,m,p=new b(function(t,v){l=t;m=v});this.ca(k(g,l),k(h,m));return p};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.ca=function(g,h){function k(){switch(l.a){case 1:g(l.f);break;case 2:h(l.f); 
break;default:throw Error("Unexpected state: "+l.a);}}var l=this;null==this.c?f.c(k):this.c.push(k);this.v=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var l=y(g),m=l.next();!m.done;m=l.next())d(m.value).ca(h,k)})};b.all=function(g){var h=y(g),k=h.next();return k.done?d([]):new b(function(l,m){function p(x){return function(w){t[x]=w;v--;0==v&&l(t)}}var t=[],v=0;do t.push(void 0),v++,d(k.value).ca(p(t.length-1),m),k=h.next(); 
while(!k.done)})};return b},"es6");u("Array.prototype.findIndex",function(a){return a?a:function(b,c){return ra(this,b,c).wa}},"es6");function ua(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[r(q.Symbol,"iterator")]=function(){return e};return e}u("Array.prototype.keys",function(a){return a?a:function(){return ua(this,function(b){return b})}},"es6"); 
u("Array.prototype.values",function(a){return a?a:function(){return ua(this,function(b,c){return c})}},"es8"); 
u("WeakMap",function(a){function b(g){this.a=(f+=Math.random()+1).toString();if(g){g=y(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}}function c(){}function d(g){var h=typeof g;return"object"===h&&null!==g||"function"===h}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),h=Object.seal({}),k=new a([[g,2],[h,3]]);if(2!=k.get(g)||3!=k.get(h))return!1;k.delete(g);k.set(h,4);return!k.has(g)&&4==k.get(h)}catch(l){return!1}}())return a;var e="$jscomp_hidden_"+Math.random(), 
f=0;b.prototype.set=function(g,h){if(!d(g))throw Error("Invalid WeakMap key");if(!sa(g,e)){var k=new c;ba(g,e,{value:k})}if(!sa(g,e))throw Error("WeakMap key fail: "+g);g[e][this.a]=h;return this};b.prototype.get=function(g){return d(g)&&sa(g,e)?g[e][this.a]:void 0};b.prototype.has=function(g){return d(g)&&sa(g,e)&&sa(g[e],this.a)};b.prototype.delete=function(g){return d(g)&&sa(g,e)&&sa(g[e],this.a)?delete g[e][this.a]:!1};return b},"es6"); 
u("Map",function(a){function b(){var h={};return h.G=h.next=h.head=h}function c(h,k){var l=h.a;return ha(function(){if(l){for(;l.head!=h.a;)l=l.G;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;"object"==l||"function"==l?f.has(k)?l=f.get(k):(l=""+ ++g,f.set(k,l)):l="p_"+k;var m=h.c[l];if(m&&sa(h.c,l))for(h=0;h<m.length;h++){var p=m[h];if(k!==k&&p.key!==p.key||k===p.key)return{id:l,list:m,index:h,l:p}}return{id:l,list:m, 
index:-1,l:void 0}}function e(h){this.c={};this.a=b();this.size=0;if(h){h=y(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),k=new a(y([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=h||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=m.value[0].x|| 
"t"!=m.value[1]||!l.next().done?!1:!0}catch(p){return!1}}())return a;var f=new q.WeakMap;e.prototype.set=function(h,k){h=0===h?0:h;var l=d(this,h);l.list||(l.list=this.c[l.id]=[]);l.l?l.l.value=k:(l.l={next:this.a,G:this.a.G,head:this.a,key:h,value:k},l.list.push(l.l),this.a.G.next=l.l,this.a.G=l.l,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.l&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.c[h.id],h.l.G.next=h.l.next,h.l.next.G=h.l.G,h.l.head=null,this.size--, 
!0):!1};e.prototype.clear=function(){this.c={};this.a=this.a.G=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).l};e.prototype.get=function(h){return(h=d(this,h).l)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value, 
h.call(k,m[1],m[0],this)};e.prototype[r(q.Symbol,"iterator")]=e.prototype.entries;var g=0;return e},"es6"); 
u("Set",function(a){function b(c){this.a=new q.Map;if(c){c=y(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.a.size}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(y([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=f.value[0].x|| 
f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;b.prototype.add=function(c){c=0===c?0:c;this.a.set(c,c);this.size=this.a.size;return this};b.prototype.delete=function(c){c=this.a.delete(c);this.size=this.a.size;return c};b.prototype.clear=function(){this.a.clear();this.size=0};b.prototype.has=function(c){return this.a.has(c)};b.prototype.entries=function(){return this.a.entries()};b.prototype.values=function(){return r(this.a,"values").call(this.a)};b.prototype.keys=r(b.prototype, 
"values");b.prototype[r(q.Symbol,"iterator")]=r(b.prototype,"values");b.prototype.forEach=function(c,d){var e=this;this.a.forEach(function(f){return c.call(d,f,f,e)})};return b},"es6");var A=this||self;function va(a){if(a&&a!=A)return xa(a.document);null===ya&&(ya=xa(A.document));return ya}var za=/^[\w+/_-]+[=]{0,2}$/,ya=null;function xa(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&za.test(a)?a:""} 
function Aa(a){a=a.split(".");for(var b=A,c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}function Ba(){}function Ca(a){a.ma=void 0;a.i=function(){return a.ma?a.ma:a.ma=new a}}function Da(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function Ea(a){return Object.prototype.hasOwnProperty.call(a,Fa)&&a[Fa]||(a[Fa]=++Ga)}var Fa="closure_uid_"+(1E9*Math.random()>>>0),Ga=0;function Ha(a,b,c){return a.call.apply(a.bind,arguments)} 
function Ia(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function Ja(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?Ja=Ha:Ja=Ia;return Ja.apply(null,arguments)} 
function Ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function B(a,b){function c(){}c.prototype=b.prototype;a.cb=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.fb=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}}function La(a){return a};var Ma=(new Date).getTime();function Na(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function Oa(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d}function Pa(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f]